import pirspic from './unstructured_content/img/thumbnail.jpg'
import pirsvid from './unstructured_content/img/pirsvid.mp4'
import hafcompic from './unstructured_content/img/hafcom.jpg'
import realpic from './unstructured_content/img/realpic.jpg'
import hafcomvid from './unstructured_content/img/HAFCOM Design Build Deliver — Mozilla Firefox 2024-06-10 09-12-05.mp4'
let projects = 
[
    {__id:"1",title:"Reporting System",picUrl:pirspic,vidurl:pirsvid,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    {__id:"2",title:"HaFCoM",picUrl:hafcompic,vidurl:hafcomvid,desc:"HafCoM is a construction and architectural company in Ethiopia. I implemented their website using react to showcase their projects and serives along with the products they offer. I learned a lot about react in this project "},
    {__id:"3",title:"RealEstate",picUrl:realpic,vidurl:"",desc:"In Ethiopia there are a lot of tiring work related to looking for properties. Noticing this problem we tried to implemet this application using the dot net framwork and the C# language. I learned in this project about the C# language and how desktop applications are implemeted. Also I learned a lot about the SQL database managment, the Entity Framework library and Object relational mappers in general. I encountered performance problems during this project and we tried to solve this problem by not saving large binary files in database instead saving them in the file system and using thier url in the database instead  "},
    // {__id:"4",title:"CPU Sched",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"5",title:"Game",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"6",title:"Fast Food",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"7",title:"Python Wef Q",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"8",title:"Security Atk",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"9",title:"CSS lib",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    // {__id:"9",title:"Producer and Cons",picUrl:pic,vidurl:vid1,desc:"In ethiopia there is a need for a reporting system. Noticing this problem me and my team tried to implement a reporting system in which the reports can be sorted by location, number of users and by the company that it is reported to. In this project we encountered multiple problems like making the user experience as frictionless as possible and trying to get as much information for the report. We tried to solve this problem by providing the user option to not repeat what other users have already reported. I learned a lot from this project like google maps api, browser geolocation api,  "},
    
]

export default projects
